# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeerSchoolFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('future_centennial_hall_food', models.TextField(null=True)),
            ],
        ),
    ]
