# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deerschoolfood',
            name='millennium_hall_food',
            field=models.TextField(null=True),
        ),
    ]
